# Pandas Project

In [3]:
import pandas as pd

In [4]:
s = pd.Series([10,20,30])
print(s)

0    10
1    20
2    30
dtype: int64

In [8]:
df = pd.DataFrame({
    "Name": ["shiva", "Rohan"],
    "marks": [85,90]
})
print(df)

    Name  marks
0  shiva     85
1  Rohan     90

In [10]:
df.to_csv("data.csv", index=False)
print("File ban gayi!")

File ban gayi!

In [11]:
df = pd.read_csv("data.csv")
print(df)

    Name  marks
0  shiva     85
1  Rohan     90

In [12]:
df.head()

    Name  marks
0  shiva     85
1  Rohan     90

In [13]:
df.tail()

    Name  marks
0  shiva     85
1  Rohan     90

In [14]:
df.shape

(2, 2)

In [15]:
df.columns

Index(['Name', 'marks'], dtype='str')

In [16]:
df.dtypes

Name       str
marks    int64
dtype: object

In [17]:
df["marks"]

0    85
1    90
Name: marks, dtype: int64

In [20]:
df[["Name", "marks"]]

    Name  marks
0  shiva     85
1  Rohan     90

In [25]:
df[df["marks"] > 50]

    Name  marks
0  shiva     85
1  Rohan     90

In [26]:
df.loc[0,"Name"]
df.iloc[0,1]

np.int64(85)

In [27]:
df.sort_values("marks", ascending=False)

    Name  marks
1  Rohan     90
0  shiva     85

In [29]:
df.isnull().sum()

Name     0
marks    0
dtype: int64

In [30]:
df.dropna

<bound method DataFrame.dropna of     Name  marks
0  shiva     85
1  Rohan     90>

In [31]:
df["marks"] = df["marks"].fillna(0)

In [32]:
df.drop_duplicates()

    Name  marks
0  shiva     85
1  Rohan     90

In [49]:
df.rename(columns={"marks":"score"},
inplace=True)

In [50]:
print(df.columns.tolist())

['Name', 'score', 'Passed']

In [51]:
df["Passed"] = df["score"] >= 40

In [52]:
print(df)

    Name  score  Passed
0  shiva     85    True
1  Rohan     90    True

In [57]:
df.groupby("Name")["score"].mean()

Name
Rohan    90.0
shiva    85.0
Name: score, dtype: float64

In [59]:
df["score"].mean()

np.float64(87.5)

In [63]:
df["score"].max()
df["score"].min()

np.int64(75)

In [65]:
df["City"].value_counts()

City
Lucknow    2
Delhi      1
Name: count, dtype: int64

In [66]:
df["City"].unique()

<StringArray>
['Lucknow', 'Delhi']
Length: 2, dtype: str

In [69]:
df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "Name": ["shiva", "Rohan", "Aman"]
})

df2 = pd.DataFrame({
    "id": [1, 2, 3],
    "score": [85, 90, 75]
})

result = pd.merge(df1, df2, on="id")
print(result)

   id   Name  score
0   1  shiva     85
1   2  Rohan     90
2   3   Aman     75

In [72]:
result=pd.merge(df1,df2,on="id")

In [74]:
pd.merge(df1,df2,on="id", how ="left")

   id   Name  score
0   1  shiva     85
1   2  Rohan     90
2   3   Aman     75

In [76]:
pd.concat([df1,df2])

   id   Name  score
0   1  shiva    NaN
1   2  Rohan    NaN
2   3   Aman    NaN
0   1    NaN   85.0
1   2    NaN   90.0
2   3    NaN   75.0

In [80]:
result = df[df["score"] > 80]
print(result)

    Name     City  score
0  shiva  Lucknow     85
1  Rohan  Lucknow     90

In [83]:
result = df.nlargest(3, "score")
print(result)

    Name     City  score
1  Rohan  Lucknow     90
0  shiva  Lucknow     85
2   Aman    Delhi     75

In [86]:
result = df.groupby("City")["score"].mean()
print(result)

City
Delhi      75.0
Lucknow    87.5
Name: score, dtype: float64

In [89]:
duplicates = df[df.duplicated()]
print(duplicates)

Empty DataFrame
Columns: [Name, City, score]
Index: []

In [90]:
print(df.isnull().sum())

Name     0
City     0
score    0
dtype: int64

In [92]:
df["marks"]=df["score"].astype(int)

In [93]:
df.to_csv("output.csv", index=False)